causalens/dara-ui

packages/ui-components/src/numeric-input/numeric-input.tsx
The numeric input’s  `width: 22ch;` is applied twice. Once from the numeric input wrapper, and once from the regular input wrapper. This makes it impossible to change the input width using `Input(value=value, type='number', width='150px')`. 
This PR disables the second width rule to prevent it from overriding the width again.
Works locally with and without the stepper.
BEFORE:
AFTER:
=> Fix: DO-1798: Fix numeric input variable width

packages/ui-components/docs/changelog.md, packages/ui-components/src/datepicker/datepicker.stories.tsx, packages/ui-components/src/datepicker/datepicker.tsx
In controlled mode in certain cases the two-way binding between the controlled datepicker value and its internal state could cause infinite loops. 
The `useEffect` hooks synchronizing the controlled value and internal states did not have any safeguards attached. 
The fix was to make sure the new controlled state is different than the internal component state before updating internal state. Otherwise this would cause a cycle in some cases:
- datepicker updates its state
- datepicker state changes, so useEffect is fired which calls props.onChange
- controlled state in parent updates (e.g. Dara Variable), causing props.value to change
- useEffect fires because of props.value change, setState is called
The loop is now stopped by bailing out of updates if the state did not change.
Added a new …
=> Fix: DO-1858 update loops in datepicker controlled mode

packages/ui-components/docs/changelog.md, packages/ui-components/src/datepicker/datepicker.tsx
There was an issue for constrained `Datepicker` where the edge years would not show as options in the dropdown.
When looking into it `lodash`'s `range` was being given the initial and end years. However in range the end bound is not included, therefore the fix was to add one to it.
None
On storybook and testing with the same range that the error was originally found
=> Fix: DO-1786 custsup datepicker doesnt show all available year choices

packages/ui-components/docs/changelog.md, packages/ui-components/src/table/render-row.tsx
Caused by #9, the rows were memoized even after the resize event. It now forces a rerender when the user is resizing any column.
Overrides the `arePropsEqual` function to look specifically at each `headerGroup` and each header inside to check if the `isResizing` flag is set on any of them. This is equivalent in behavior to the one before #9.
None
Storybook
=> Fix: DO-1833: Fix table header resizing

packages/ui-causal-graph-editor/docs/changelog.md, packages/ui-causal-graph-editor/src/graph-viewer/graph-editor.stories.tsx, packages/ui-causal-graph-editor/src/shared/editor-overlay/panel-content/edge/sections/constraint-editor.tsx, packages/ui-causal-graph-editor/src/shared/rendering/edge/symbols.tsx, packages/ui-causal-graph-editor/src/shared/use-edge-encoder.tsx, packages/ui-causal-graph-editor/src/types.tsx
With release of 0.3.0 of `cai-causal-graph` there have been changes to how constraint edges are defined:
https://github.com/causalens/cai-causal-graph/commit/e47ee4357fc5ec8291c3d548438b4f4fbea1170f
Update `EdgeConstraintType` to have the same values as the newly defined. At the moment I have made so that SOFT_DIRECTED and HARD_DIRECTED will behave and look in the same way. We can later add different visual representations for them once we have an idea for what this should be. 
There will be accompanying PRs across dara, and ui internal, dara internal adapting to these changes.
None
Locally on Storybook
=> Fix: DO-2086 update edge constraints in visual edge encoder

packages/ui-causal-graph-editor/docs/changelog.md, packages/ui-causal-graph-editor/src/graph-viewer/causal-graph-editor.tsx, packages/ui-causal-graph-editor/src/shared/serializer.tsx, packages/ui-causal-graph-editor/src/types.tsx, packages/ui-causal-graph-editor/tests/causal-graph-parser.spec.tsx, packages/ui-causal-graph-editor/tests/causal-graph-serializer.spec.tsx, packages/ui-causal-graph-editor/tests/causal-graph-store.spec.tsx, packages/ui-causal-graph-editor/tests/mocks/extras-graph.tsx, packages/ui-causal-graph-editor/tests/utils.tsx
`CausalGraph`'s edge `source`/`destination` fields are no longer strings, but objects containing a copy of the node info. Additionally, each node now has a `node_class` field.
Modifies `serializeGraphEdge` to include the node info. Since `onClickEdge` callback also uses it, its signature was updated to return a node object instead of a string as well.
Tests were updated accordingly. The mock causal graph now includes source/destination fields.
=> Feat: DO-2140: Support edge source/destination attributes for CausalGraphEditor

packages/ui-causal-graph-editor/docs/changelog.md, packages/ui-causal-graph-editor/src/shared/rendering/engine.tsx
This PR fixes an issue where dragging would not work correctly when moving the mouse too quickly, particularly in non-editable mode. 
To reproduce previously:
- run graph in non-editable mode with a layout which allows node drag (e.g. fCoSE)
- attempt to drag a node - moving mouse quickly works, but if the cursor ends up outside of the node the dragging breaks rather than adjusting the node position further
https://github.com/causalens/dara-ui/assets/87647189/77530aac-43ac-4054-a8f5-24fb6cb163d6
The issue was due to the `mousedownNodeKey` (variable holding which node was originally pressed at the start of drag) being reset on `mouseout`, even while dragging. The regression was traced back to PR 275 in the old (closed source) repo. 
Fixed by adding a guard to only reset the mouse down node …
=> Fix: DO-2267 DO-2281 drag nodes not working correctly

packages/ui-components/docs/changelog.md, packages/ui-components/src/datepicker/datepicker.stories.tsx, packages/ui-components/src/datepicker/datepicker.tsx
User feedback that datepicker was annoying to use as when we selected the end date input it still forced user to select the whole range again.
Applied `selectsStart ` and  `selectsEnd` to ReactDatepicker. This allows us to define the behaviour of the range selected based on the input which has been interacted with.
Also had to make some CSS changes so that the behaviour as you select values in the range looked as you would expect. This behaviour is shown in the gif below.
=> Fix: DO-2112 datepicker with range when selecting end date overwrites start date

packages/ui-components/docs/changelog.md, packages/ui-components/src/context-menu/context-menu.tsx
It was reported that the first option of the context menu can be easily clicked by accident, especially when using a touchpad.
This is now improved by offsetting the menu position a few pixels away from the cursor which matches closely the native context menu behaviour.
Storybook
https://github.com/causalens/dara-ui/assets/87647189/40384ebf-d4a5-4458-b082-9e232ba85839
=> Improvement: DO-2449 offset `ContextMenu` few pixels from the cursor

packages/ui-causal-graph-editor/docs/changelog.md, packages/ui-causal-graph-editor/src/graph-viewer/causal-graph-editor.tsx, packages/ui-causal-graph-editor/src/graph-viewer/graph-editor.stories.tsx, packages/ui-causal-graph-editor/src/index.tsx, packages/ui-causal-graph-editor/src/shared/editor-overlay/index.tsx, packages/ui-causal-graph-editor/src/shared/editor-overlay/legend/index.tsx, packages/ui-causal-graph-editor/src/shared/editor-overlay/legend/legend-data.tsx, packages/ui-causal-graph-editor/src/shared/editor-overlay/legend/legend-list.tsx, packages/ui-causal-graph-editor/src/shared/editor-overlay/legend/legend.tsx
Make adding custom legend to graphs easier, also expand it to also allow to define nodes in the legend
I have updated the type of `additionalLegends` to accept a set of equal props: label, type and symbol which together can be used to define the legend the user wants to show in the graph. It now accepts a list of `GraphLegendDefinition`. 
You can define it as:
```
{
label: my label
type: node
symbol: {
color: red
}
} 
```
Depending on the type chosen symbol takes either node properties or edge properties. These are optional and if not set just show the default node/edge color/style. If type is set to none, the user can use that to show a spacer.
Dara side tickets to follow
None
=> Improvement: DO-1585 custsup ability to add custom legends to causalgraphviewer (1/4)

packages/ui-components/docs/changelog.md, packages/ui-components/src/dropzone/dropzone.tsx
Right now `UploadDropzone` includes an unconditional event handler for any `paste` event. This is fine for use in full-page apps, but presents a problem when it is used in larger pages with multiple components.
This PR adds an `enablePaste` prop that will control whether the `paste` event listener is enabled or not. By default, it is now disabled, requiring explicit activation.
Locally. It looks like storybook doesn't forward the paste event, so just send it manually:
```tsx
function triggerPasteEvent(text) {
const event = new ClipboardEvent('paste', {
bubbles: true,
cancelable: true,
clipboardData: new DataTransfer()
});
event.clipboardData.setData('text/plain', text);
document.dispatchEvent(event);
} 
```
=> Improvement: DO-2575: Disable UploadDropzone paste event by default

packages/ui-causal-graph-editor/docs/changelog.md, packages/ui-causal-graph-editor/src/graph-viewer/causal-graph-editor.tsx, packages/ui-causal-graph-editor/src/shared/editor-overlay/overlay.tsx, packages/ui-causal-graph-editor/src/shared/editor-overlay/positional-divs.tsx, packages/ui-causal-graph-editor/src/shared/editor-overlay/zoom-prompt.tsx, packages/ui-causal-graph-editor/src/shared/rendering/engine.tsx, packages/ui-causal-graph-editor/src/shared/rendering/use-render-engine.tsx, packages/ui-components/docs/changelog.md
Users reported frustrations with the current behaviour where the graph zooms when using the mousewheel to scroll by default. While this is mostly fine for large graphs, if the content itself becomes scrollable this can make it difficult to navigate the page.
This PR makes the behaviour disabled by default - the graph now requires clicking on it to enable the wheel scroll behaviour. This is indicated with a grey focus outline (see gif at the bottom)
This behaviour can be changed to restore the previous one, by providing a prop `requireFocusToZoom` set to false.
The first time the user encounters a graph with the new behaviour turned on they will see a prompt on top explaining the behaviour:
Once a graph is focused an outline is displayed and the prompt changes:
The prompt can be dismissed …
=> Improvement: DO-2603 require click on canvas to zoom with mousewheel for graph viewer

packages/ui-causal-graph-editor/docs/changelog.md, packages/ui-causal-graph-editor/src/graph-viewer/causal-graph-editor.tsx, packages/ui-causal-graph-editor/src/graph-viewer/graph-editor.stories.tsx, packages/ui-causal-graph-editor/src/shared/editor-overlay/zoom-prompt.tsx, packages/ui-causal-graph-editor/src/shared/use-graph-tooltip.tsx, packages/ui-causal-graph-editor/src/shared/use-pane-visibility.tsx
The original causal graph viewer tooltip implementation did not account for the viewer being out of view due to overflowing in e.g. a scrollable container or a collapse/accordion style component.
This resulted in the tooltips being displayed in seemingly random places, when hovering over where the graph would be if it wasn't for the fact that it's currently hidden. There were also other quirks where the tooltip wouldn't disappear correctly when moving the mouse out of the graph.
Implemented few fixes:
1. Tooltip is now explicitly set to null `onMouseLeave` of the graph pane - this fixes scenarios where a node is right on the border of the graph view, and previously moving the mouse out of the view kept the tooltip on. Also added a `contentvisibility` listener so focusing out of the window …
=> Fix: DO-2692 causal graph tooltip quirks with visibility

packages/ui-causal-graph-editor/docs/changelog.md, packages/ui-causal-graph-editor/src/shared/rendering/engine.tsx
There are scenarios where with layout shifts on a page (i.e. a py_component rendering) sometimes the graph has to resize itself after its initial layout computation. This causes the original layout to be wrong which can be annoying for users.
As a compromise the solution here is to recalculate the layout after a resize was detected. While this will potentially have destructive effect on a hand-crafted layout (i.e. after user shuffled nodes arounds manually and something shifted, the recalculate button will effectively be clicked for them), this should not a a common scenario and more often than not will be an improvement to the UX. If the downside becomes severe we can prioritize features such as being able to save and restore a custom layout.
There was already a resize observer attached …
=> Improvement: DO-2661 recalculate layout on pane resize

packages/ui-components/docs/changelog.md, packages/ui-components/src/chat/message.tsx
When pasting an url in chat it would overflow the container instead or wrapping
Added `overflow-wrap: break-word;` so that if a word is too long to fit in one line alone it will break. This is useful in the case of for example pasting urls.
=> Fix: DO-2740 chat messages do not wrap the text

packages/ui-components/docs/changelog.md, packages/ui-components/src/chat/chat.tsx, packages/ui-components/src/chat/message.tsx
It was noted that after page refreshes any enters entered would show as \n and then `\\n`etc.
For now I am just removing any \n and trailing white space for messages. In the future we will go back into this to display these properly.
None
Locally on storybook logging the message values to see if any \n were adequately removed
=> Fix: DO-2743 chat message adding a n at the end on reload

packages/ui-causal-graph-editor/docs/changelog.md, packages/ui-causal-graph-editor/src/graph-viewer/causal-graph-editor.tsx, packages/ui-causal-graph-editor/src/shared/causal-graph-store.tsx, packages/ui-causal-graph-editor/src/shared/use-causal-graph-editor.tsx, packages/ui-causal-graph-editor/tests/causal-graph-store.spec.tsx
When an edge was added and the CausalGraphViewer did not have editorMode defined then it always added edges as undirected.
If editorMode is not defined we check if the graph is a DAG if so we default to DEFAULT editor mode, otherwise it is set to PAG. 
This is done within the causal-graph-editor file once we have the state of the graph. However the ability to add edges is done within the reducer where this information was not yet available. 
The suggested approach was just to add the dag check within the add edge method of the reducer.
None
Locally on storybook and by adding tests to cover this scenario
=> Fix: DO-2772 edges added as undirected in editable mode

packages/ui-causal-graph-editor/docs/changelog.md, packages/ui-causal-graph-editor/src/shared/rendering/engine.tsx
A user had issues with the graph recalculating layout when trying to zoom in and inspect it
Although the cause of the issue the user experienced is not fully known as we were not able to recreate it, in the video showing the issue we see that before the resize took place scroll bars were added which would change the canvas size triggering a recalculation. With this in mind the suggested approach is that we should only resize on canvas size change if the graph is not focused. Which seems more desirable as if you are actively interacting with a graph you probably don't want it to change due to external factors.
None
=> Improvement: DO-2894 graph resizing issue

packages/ui-causal-graph-editor/docs/changelog.md, packages/ui-causal-graph-editor/src/shared/graph-layout/fcose-layout.tsx
User came across an issue with CausalGraphViewer on Jupyter where it would crash when adding a nodes to the tiers array object that did not exist in their causal graph.
Although the user was using PlanarLayout, upon closer examination the layout was being defaulted to Fcose since the tiers could not be resolved. After some testing this was found to be an Fcose specific issue where since it couldn't find the node to add relative positioning to it crashed. 
The fix was for when an array of array of nodes is passed as a tier to Fcose, for us to filter it, guaranteeing that only nodes in the graph are added to the tiered positioning calculations.
None
=> Fix: DO-2780 nodes not present in tiers hangs indefinitely on jupyter

packages/ui-causal-graph-editor/docs/changelog.md, packages/ui-causal-graph-editor/src/graph-viewer/causal-graph-editor.tsx, packages/ui-causal-graph-editor/src/graph-viewer/graph-editor.stories.tsx, packages/ui-causal-graph-editor/src/shared/graph-layout/fcose-layout.tsx, packages/ui-causal-graph-editor/src/shared/graph-layout/force-atlas-layout.tsx, packages/ui-causal-graph-editor/src/shared/rendering/use-render-engine.tsx, packages/ui-causal-graph-editor/src/shared/use-pane-visibility.tsx
This PR fixes the issue where the graph component would crash if there were no nodes in the graph.
There was a piece of rendering logic which meant that the graph canvas would not render if there were no nodes; instead, a message 'graph is empty' is displayed.
There were certain pieces of logic which made assumptions on the graph canvas being defined, these have now been fixed.
I've also adjusted the logic to display the blank canvas in editable mode - this is a valid use case as it can be used to build up the graph from scratch. I've left the message for non-editable mode as then there's no point displaying the UI. 
I'm happy to just render the blank canvas in both cases though, let me know if you think that's better.
Locally
Added a storybook story for the empty case
=> Fix: DO-2961 empty causal graph crashes the component

packages/ui-components/docs/changelog.md, packages/ui-components/src/multiselect/multiselect.tsx
Fixed a crash when `null` was passed to `MultiSelect`'s `selectedItems` prop.
Downshift was handling the case when it's `undefined` correctly, but was failing when `null` was passed. Related recent change on the dara side: https://github.com/causalens/dara/pull/298.
Given that this happens to dara-ui as well, it's better to implement this change here instead of on the dara side.
Related discussion: https://github.com/causalens/dara/issues/307.
Works correctly now when passing `null`, `undefined`, `nothing`, or any element outside of the list of items.
=> Fix: DO-3044: Fix Multiselect crash when `null` is passed as `selectedItems`

packages/ui-components/docs/changelog.md, packages/ui-components/src/switch/switch.tsx
Switch component appeared slightly off centre when the base font was 14px instead of 16px:
Fixed to use `rem` instead of `px`
None
Locally by changing the base font size to a range of different values and checking the circle kept centred
=> Fix: DO-3116: switch component circle appears off centre on different base font

packages/ui-causal-graph-editor/docs/changelog.md, packages/ui-causal-graph-editor/src/shared/rendering/engine.tsx, packages/ui-causal-graph-editor/src/shared/rendering/grouping/definitions.tsx, packages/ui-causal-graph-editor/src/shared/rendering/grouping/group-container-object.tsx
As UAT feedback it was found that in some cased the nodes could escape their containers/groups
Looking into it the container updated size, but as you hovered out of it, it triggered another update of style which forces it to recalculate its size. In some environments when moving too quickly it seems that this update could get old positions for the nodes and so update the container to some previous size and position. Resulting in the dragged node appearing outside of its container.
We don't actually use a hover state to draw the container. This was left over from an early stage of implementation where I wasn't sure if it would be needed. Since it is not used it has been removed.
None
By running an app on dara side with the changes as the error did not seem to happen on storybook
=> Fix: DO-3186 write and address uat ticket for node grouping in graph layouts

packages/ui-causal-graph-editor/docs/changelog.md, packages/ui-causal-graph-editor/src/graph-viewer/storybook/fcose.stories.tsx, packages/ui-causal-graph-editor/src/shared/rendering/engine.tsx, packages/ui-causal-graph-editor/src/shared/use-causal-graph-editor.tsx
1. Layout calculation was done twice for the first render due to both the original `updateLayout` calculation and a `debouncedUpdateLayout` on `ResizeObserver`. The graph now stores its previous size and only recalculates the layout if the size actually changed.
This results in ~33% reduction in first frame render time.
2. A similar issue was found in the `useCausalGraphEditor` update effect. The `causalGraphParser` was called twice. 
Just reusing the result reduced the update time by another ~33%.
Modified the random cluster story to allow profiling first frame render times.
BEFORE:
AFTER:
BEFORE:
AFTER:
=> Improvement: DO-3223: Skip recalculating graph layout if size hasn't changed
